### ISSUE TITLE
Multimap serializer doesn't work with non-String keys, even if it seems like they should.

### ISSUE THREAD

**Issue by stevenschlansker** [FasterXML/jackson-datatype-guava#13]
Serializing a Multimap<K, ?> fails if K is any non-String type, even if intuitively it should work (e.g. K is a string-like type such as Enum, or K has an `@JsonValue` annotation).

I couldn't figure out how this is supposed to work, so I have included failing test cases for both the 1.9 branch and 2.x branch and hope that someone else who knows more about how Jackson's typing works can help out.

**Comment by ta-cpwr** [comment]
We have a Multimap with Enum keys.
`MultimapBuilder.enumKeys(CloudProvider.class).arrayListValues().build()`
The Jackson `ObjectMapper` has the `SerializationFeature.WRITE_ENUMS_USING_TO_STRING` set to _false_, as well as `WRITE_ENUMS_USING_INDEX` set to _false_.
We therefore would expect the keys of the Multimap to be serialized via `Enum.name()`
But instead they are serialized as `Enum.toString()`
(c.f. `EnumMapSerializer`)

**Comment by cowtowncoder** [comment]
Could this be same as:

https://github.com/FasterXML/jackson-databind/issues/749

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-datatypes-collections/issues/3
