### ISSUE TITLE
better multiset serialization / deserialization

### ISSUE THREAD

**Issue by devinrsmith** [FasterXML/jackson-datatype-guava#51]
Currently, multisets' serialization size is proportional to Multiset.size() as opposed to Multiset.entrySet().size().

For example, if I have do Multiset\<String\>.setCount("my_key", 1000), "my_key" is repeated 1000 times in the output. It would be much more appropriate if it behaved liked Map\<String, Integer\>.

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-datatypes-collections/issues/2
