### ISSUE TITLE
fasterxml/jackson/datatype/guava/ser/MultimapSerializer.java cause null pointer exception when some value is null

### ISSUE THREAD

**Issue by sixinli** [FasterXML/jackson-datatype-guava#61]
multimap with null values triggers null pointer exception at line 296

**Comment by cowtowncoder** [comment]
Thank you for reporting this! Fixed for 2.5.1 (and 2.4.6 if that is released)

**Comment by derekcicerone** [comment]
Wow, that was fast! Thanks for the quick fix.
