### ISSUE TITLE
[question] How to set a default lowerBoundType and upperBoundType?

### ISSUE THREAD

**Issue by jorool** [FasterXML/jackson-datatype-guava#76]
Hello!
I want to deserialize an object like this, without explicitly inform lowerBoundType and upperBoundType:

```
{
  foo: 'bar',
  fooz: {
    lowerEndpoint: 1,
    upperEndpoint: 5
  }
}
```

How can I configure the deserializer to aways set lowerBoundType and upperBoundType as 'CLOSED'?

**Comment by cowtowncoder** [comment]
Could you include matching POJO you are thinking of, including type of value? (`Range`?)

**Comment by jorool** [comment]
@cowtowncoder sure!
In this case I have 2 different range attributes:

```
public class PerfilImovel extends stuff.. {
    //stuff
    private Range<ValorMonetario> faixaDePreco = Range.all();
    private Range<Integer> quartos = Range.all();
    //more stuff
}
```

For now, ValorMonetario is a value object serialized as a simple string.
To persist a new PerfilImovel I post a JSON like this:

```
{
  //stuff
  faixaDePreco.lowerEndpoint: 123456.78,
  faixaDePreco.upperEndpoint: 1234567.89,
  faixaDePreco.lowerBoundType: 'CLOSED',
  faixaDePreco.upperBoundType: 'CLOSED'
  //more stuff
}
```

BUT, to get this working I hard coded in my JS controller this:

```
    if (item.perfilImovel.faixaDePreco) {
        item.perfilImovel.faixaDePreco.lowerBoundType = 'CLOSED';
        item.perfilImovel.faixaDePreco.upperBoundType = 'CLOSED';
    }
```

This solves the error "lowerBoundType/upperBoundType not present..." or something like that.
I believe I can get rid of that code with a simple config that tells the deserializer that I aways want to use closed ranges.

What do you think?

**Comment by cowtowncoder** [comment]
I don't know how this could be achieved, but perhaps you can have a look at `RangeDeserializer` to see if you could simply sub-class it, and register your custom deserializer instead of default one?

**Comment by jorool** [comment]
@cowtowncoder I have an idea of what we can do, but not sure of how to get it done. Can you take a look at pull request #77? There's some TODO comments that trying to explain my doubts.

**Comment by jorool** [comment]
@cowtowncoder I've updated the PR #77. There's a failing test for version number. I'm not sure if I should "solve" it...
```
TestVersions.testMapperVersions:16->assertVersion:35 expected:<2.6.1-SNAPSHOT> but was:<2.6.0>
```

**Comment by jorool** [comment]
@cowtowncoder PR #77 closed. The new PR is #79 .

**Comment by cowtowncoder** [comment]
@jorool Correct: this change can not be made in a patch release and has to go in a minor version, as it changes the API.
