### ISSUE TITLE
Class not found exception in OSGi (com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter)

### ISSUE THREAD

**Issue by mjameson-se** [FasterXML/jackson-datatype-guava#84]
Just upgraded my project dependencies to 2.6.2 (from 2.5.1), starting seeing an exception on serialization complaining about com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter not being found. Looks like the guava module jar does not have an import directive for that package. Ideally, it shouldn't have to since you guys aren't using that class directly. However, in order for it to all work, the package you're importing from needs to have "uses" directives attached to their Export-Package entries which specify their transitive package dependencies.

**Comment by cowtowncoder** [comment]
Ok, thank you for reporting this. There is actually a dependency to it from within code that handles `Optional`. Going forward it may make sense to just rely on auto-generated dependencies, although for 2.6.3 I may just add import explicitly, to minimize risk of unrelated breakage (that is, in case auto-generation has some problems -- adding that for 2.7 gives more testing than doing it in a patch).
