### ISSUE TITLE
OSGi import package(s?) missing in 2.7.0

### ISSUE THREAD

**Issue by mjameson-se** [FasterXML/jackson-datatype-guava#87]
Trying to upgrade to 2.7.0 jackson-datatype-guava, I'm getting exceptions "Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude$Value". It looks like the import statement for that package is missing

Currently, I'm using a hacked up version of 2.6.2 using bnd to rewrite the manifest because that one was also missing entries.

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Will fix for 2.7.1.

**Comment by cowtowncoder** [comment]
Added OSGi import, should work now. It's unfortunate that explicit inclusion directive is needed, unlike with most other components, to support wider version range for Guava. Would also be great if there was an automated way to verify completeness of inclusion.

**Comment by mjameson-se** [comment]
For what its worth, bnd is capable of doing what you really want. I'm not familiar enough with the maven plugin you're using that wraps bnd to know if it is possible to do it through that or how to do so, but I've done it in different projects using bndtools and gradle respectively.

**Comment by cowtowncoder** [comment]
@mjameson-se Yes, I know, as I said other modules do that. I am just not sure if automatic calculation can be combined with alternative version range modifiers. Or, rather, how to change; quite possibly it is possible. If anyone knows how to do that, would love to improve setup.
