### ISSUE TITLE
Does not honor DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY

### ISSUE THREAD

**Issue by neilmcguigan** [FasterXML/jackson-datatype-guava#89]
Should be able to have

`enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);`

```
class Foo {
    public Multimap<String,String> bar;
}
```

with JSON

```
{
  bar: "qux"
}
```

However, this throws exception:

`JsonMappingException: Expecting START_ARRAY, found VALUE_STRING`

Please note that this works:

```
class Foo {
    List<String> bar;
}
```

with JSON:

```
{
  bar: "qux"
}
```

when `enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);`

**Comment by cowtowncoder** [comment]
Thank you for reporting this! Moved this to https://github.com/FasterXML/jackson-datatypes-collections/issues/6

since this repository is deprecated (but is retained to be able to publish older versions)
