### ISSUE TITLE
Support for Table deseriailzation

### ISSUE THREAD

**Issue by trothwell** [FasterXML/jackson-datatype-guava#91]
What can be done to support Table deserialization?

I only see a "TODO".

https://github.com/FasterXML/jackson-datatype-guava/blob/master/src/main/java/com/fasterxml/jackson/datatype/guava/GuavaDeserializers.java#L237

**Comment by cowtowncoder** [comment]
Typically someone with an itch implements the addition, submits a Pull Request.
In this particular case feature is bit tricky as there are multiple possible approaches; on plus side perhaps it'd be possible to make use of existing PR fragments.

Note, too, that this repo is closed; so any new issues and discussions should go to new repo; and this particular issue exists here:

https://github.com/FasterXML/jackson-datatypes-collections/issues/1
